// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Millonario.Infrastructure;

#nullable disable

namespace Millonario.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250521061409_InitialMigrationWithAllData")]
    partial class InitialMigrationWithAllData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Millonario.Domain.Pregunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NivelDificultad")
                        .HasColumnType("int");

                    b.Property<string>("TextoPregunta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Preguntas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Geografía",
                            NivelDificultad = 1,
                            TextoPregunta = "¿Cuál es la capital de Francia?"
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Astronomía",
                            NivelDificultad = 1,
                            TextoPregunta = "¿Qué planeta es conocido como el Planeta Rojo?"
                        },
                        new
                        {
                            Id = 6,
                            Categoria = "Geografía",
                            NivelDificultad = 1,
                            TextoPregunta = "¿Cuál es el río más largo del mundo (considerando solo longitud)?"
                        },
                        new
                        {
                            Id = 7,
                            Categoria = "Arte",
                            NivelDificultad = 1,
                            TextoPregunta = "¿Quién pintó la 'Mona Lisa'?"
                        },
                        new
                        {
                            Id = 8,
                            Categoria = "Geografía",
                            NivelDificultad = 1,
                            TextoPregunta = "¿Cuál es la capital de Japón?"
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Literatura",
                            NivelDificultad = 2,
                            TextoPregunta = "¿Quién escribió 'Cien años de soledad'?"
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "Ciencia",
                            NivelDificultad = 2,
                            TextoPregunta = "¿Cuál es el elemento químico más abundante en la corteza terrestre?"
                        },
                        new
                        {
                            Id = 9,
                            Categoria = "Matemáticas",
                            NivelDificultad = 2,
                            TextoPregunta = "¿Cuántos lados tiene un heptágono?"
                        },
                        new
                        {
                            Id = 10,
                            Categoria = "Biología",
                            NivelDificultad = 2,
                            TextoPregunta = "¿Qué animal es el mamífero terrestre más grande?"
                        },
                        new
                        {
                            Id = 13,
                            Categoria = "Ciencia",
                            NivelDificultad = 2,
                            TextoPregunta = "¿Quién descubrió la penicilina?"
                        },
                        new
                        {
                            Id = 5,
                            Categoria = "Historia",
                            NivelDificultad = 3,
                            TextoPregunta = "¿En qué año se disolvió la Unión Soviética?"
                        },
                        new
                        {
                            Id = 11,
                            Categoria = "Economía",
                            NivelDificultad = 3,
                            TextoPregunta = "¿Cuál es la moneda oficial de China?"
                        },
                        new
                        {
                            Id = 12,
                            Categoria = "Geografía",
                            NivelDificultad = 3,
                            TextoPregunta = "¿Cuál es el país con más población del mundo?"
                        },
                        new
                        {
                            Id = 14,
                            Categoria = "Anatomía",
                            NivelDificultad = 3,
                            TextoPregunta = "¿Cuál es el hueso más largo del cuerpo humano?"
                        },
                        new
                        {
                            Id = 15,
                            Categoria = "Música",
                            NivelDificultad = 3,
                            TextoPregunta = "¿Qué compositor es conocido por la 'Novena Sinfonía'?"
                        });
                });

            modelBuilder.Entity("Millonario.Domain.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaRecord")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("Millonario.Domain.Respuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsCorrecta")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PreguntaId")
                        .HasColumnType("int");

                    b.Property<string>("TextoRespuesta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.ToTable("Respuestas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EsCorrecta = true,
                            PreguntaId = 1,
                            TextoRespuesta = "París"
                        },
                        new
                        {
                            Id = 2,
                            EsCorrecta = false,
                            PreguntaId = 1,
                            TextoRespuesta = "Londres"
                        },
                        new
                        {
                            Id = 3,
                            EsCorrecta = false,
                            PreguntaId = 1,
                            TextoRespuesta = "Madrid"
                        },
                        new
                        {
                            Id = 4,
                            EsCorrecta = false,
                            PreguntaId = 1,
                            TextoRespuesta = "Berlín"
                        },
                        new
                        {
                            Id = 5,
                            EsCorrecta = false,
                            PreguntaId = 2,
                            TextoRespuesta = "Júpiter"
                        },
                        new
                        {
                            Id = 6,
                            EsCorrecta = true,
                            PreguntaId = 2,
                            TextoRespuesta = "Marte"
                        },
                        new
                        {
                            Id = 7,
                            EsCorrecta = false,
                            PreguntaId = 2,
                            TextoRespuesta = "Venus"
                        },
                        new
                        {
                            Id = 8,
                            EsCorrecta = false,
                            PreguntaId = 2,
                            TextoRespuesta = "Saturno"
                        },
                        new
                        {
                            Id = 9,
                            EsCorrecta = true,
                            PreguntaId = 6,
                            TextoRespuesta = "Nilo"
                        },
                        new
                        {
                            Id = 10,
                            EsCorrecta = false,
                            PreguntaId = 6,
                            TextoRespuesta = "Amazonas"
                        },
                        new
                        {
                            Id = 11,
                            EsCorrecta = false,
                            PreguntaId = 6,
                            TextoRespuesta = "Yangtsé"
                        },
                        new
                        {
                            Id = 12,
                            EsCorrecta = false,
                            PreguntaId = 6,
                            TextoRespuesta = "Mississippi"
                        },
                        new
                        {
                            Id = 13,
                            EsCorrecta = false,
                            PreguntaId = 7,
                            TextoRespuesta = "Vincent van Gogh"
                        },
                        new
                        {
                            Id = 14,
                            EsCorrecta = false,
                            PreguntaId = 7,
                            TextoRespuesta = "Pablo Picasso"
                        },
                        new
                        {
                            Id = 15,
                            EsCorrecta = true,
                            PreguntaId = 7,
                            TextoRespuesta = "Leonardo da Vinci"
                        },
                        new
                        {
                            Id = 16,
                            EsCorrecta = false,
                            PreguntaId = 7,
                            TextoRespuesta = "Claude Monet"
                        },
                        new
                        {
                            Id = 17,
                            EsCorrecta = false,
                            PreguntaId = 8,
                            TextoRespuesta = "Pekín"
                        },
                        new
                        {
                            Id = 18,
                            EsCorrecta = false,
                            PreguntaId = 8,
                            TextoRespuesta = "Seúl"
                        },
                        new
                        {
                            Id = 19,
                            EsCorrecta = true,
                            PreguntaId = 8,
                            TextoRespuesta = "Tokio"
                        },
                        new
                        {
                            Id = 20,
                            EsCorrecta = false,
                            PreguntaId = 8,
                            TextoRespuesta = "Bangkok"
                        },
                        new
                        {
                            Id = 21,
                            EsCorrecta = true,
                            PreguntaId = 3,
                            TextoRespuesta = "Gabriel García Márquez"
                        },
                        new
                        {
                            Id = 22,
                            EsCorrecta = false,
                            PreguntaId = 3,
                            TextoRespuesta = "Mario Vargas Llosa"
                        },
                        new
                        {
                            Id = 23,
                            EsCorrecta = false,
                            PreguntaId = 3,
                            TextoRespuesta = "Julio Cortázar"
                        },
                        new
                        {
                            Id = 24,
                            EsCorrecta = false,
                            PreguntaId = 3,
                            TextoRespuesta = "Jorge Luis Borges"
                        },
                        new
                        {
                            Id = 25,
                            EsCorrecta = false,
                            PreguntaId = 4,
                            TextoRespuesta = "Hierro"
                        },
                        new
                        {
                            Id = 26,
                            EsCorrecta = true,
                            PreguntaId = 4,
                            TextoRespuesta = "Oxígeno"
                        },
                        new
                        {
                            Id = 27,
                            EsCorrecta = false,
                            PreguntaId = 4,
                            TextoRespuesta = "Silicio"
                        },
                        new
                        {
                            Id = 28,
                            EsCorrecta = false,
                            PreguntaId = 4,
                            TextoRespuesta = "Aluminio"
                        },
                        new
                        {
                            Id = 29,
                            EsCorrecta = false,
                            PreguntaId = 9,
                            TextoRespuesta = "6"
                        },
                        new
                        {
                            Id = 30,
                            EsCorrecta = true,
                            PreguntaId = 9,
                            TextoRespuesta = "7"
                        },
                        new
                        {
                            Id = 31,
                            EsCorrecta = false,
                            PreguntaId = 9,
                            TextoRespuesta = "8"
                        },
                        new
                        {
                            Id = 32,
                            EsCorrecta = false,
                            PreguntaId = 9,
                            TextoRespuesta = "5"
                        },
                        new
                        {
                            Id = 33,
                            EsCorrecta = false,
                            PreguntaId = 10,
                            TextoRespuesta = "Ballena Azul"
                        },
                        new
                        {
                            Id = 34,
                            EsCorrecta = true,
                            PreguntaId = 10,
                            TextoRespuesta = "Elefante Africano"
                        },
                        new
                        {
                            Id = 35,
                            EsCorrecta = false,
                            PreguntaId = 10,
                            TextoRespuesta = "Jirafa"
                        },
                        new
                        {
                            Id = 36,
                            EsCorrecta = false,
                            PreguntaId = 10,
                            TextoRespuesta = "Rinoceronte"
                        },
                        new
                        {
                            Id = 37,
                            EsCorrecta = false,
                            PreguntaId = 13,
                            TextoRespuesta = "Marie Curie"
                        },
                        new
                        {
                            Id = 38,
                            EsCorrecta = false,
                            PreguntaId = 13,
                            TextoRespuesta = "Louis Pasteur"
                        },
                        new
                        {
                            Id = 39,
                            EsCorrecta = true,
                            PreguntaId = 13,
                            TextoRespuesta = "Alexander Fleming"
                        },
                        new
                        {
                            Id = 40,
                            EsCorrecta = false,
                            PreguntaId = 13,
                            TextoRespuesta = "Robert Koch"
                        },
                        new
                        {
                            Id = 41,
                            EsCorrecta = false,
                            PreguntaId = 5,
                            TextoRespuesta = "1989"
                        },
                        new
                        {
                            Id = 42,
                            EsCorrecta = true,
                            PreguntaId = 5,
                            TextoRespuesta = "1991"
                        },
                        new
                        {
                            Id = 43,
                            EsCorrecta = false,
                            PreguntaId = 5,
                            TextoRespuesta = "1993"
                        },
                        new
                        {
                            Id = 44,
                            EsCorrecta = false,
                            PreguntaId = 5,
                            TextoRespuesta = "1985"
                        },
                        new
                        {
                            Id = 45,
                            EsCorrecta = false,
                            PreguntaId = 11,
                            TextoRespuesta = "Yen"
                        },
                        new
                        {
                            Id = 46,
                            EsCorrecta = false,
                            PreguntaId = 11,
                            TextoRespuesta = "Won"
                        },
                        new
                        {
                            Id = 47,
                            EsCorrecta = true,
                            PreguntaId = 11,
                            TextoRespuesta = "Yuan"
                        },
                        new
                        {
                            Id = 48,
                            EsCorrecta = false,
                            PreguntaId = 11,
                            TextoRespuesta = "Rublo"
                        },
                        new
                        {
                            Id = 49,
                            EsCorrecta = false,
                            PreguntaId = 12,
                            TextoRespuesta = "Rusia"
                        },
                        new
                        {
                            Id = 50,
                            EsCorrecta = true,
                            PreguntaId = 12,
                            TextoRespuesta = "India"
                        },
                        new
                        {
                            Id = 51,
                            EsCorrecta = false,
                            PreguntaId = 12,
                            TextoRespuesta = "Estados Unidos"
                        },
                        new
                        {
                            Id = 52,
                            EsCorrecta = false,
                            PreguntaId = 12,
                            TextoRespuesta = "China"
                        },
                        new
                        {
                            Id = 53,
                            EsCorrecta = false,
                            PreguntaId = 14,
                            TextoRespuesta = "Tibia"
                        },
                        new
                        {
                            Id = 54,
                            EsCorrecta = true,
                            PreguntaId = 14,
                            TextoRespuesta = "Fémur"
                        },
                        new
                        {
                            Id = 55,
                            EsCorrecta = false,
                            PreguntaId = 14,
                            TextoRespuesta = "Húmero"
                        },
                        new
                        {
                            Id = 56,
                            EsCorrecta = false,
                            PreguntaId = 14,
                            TextoRespuesta = "Radio"
                        },
                        new
                        {
                            Id = 57,
                            EsCorrecta = false,
                            PreguntaId = 15,
                            TextoRespuesta = "Wolfgang Amadeus Mozart"
                        },
                        new
                        {
                            Id = 58,
                            EsCorrecta = true,
                            PreguntaId = 15,
                            TextoRespuesta = "Ludwig van Beethoven"
                        },
                        new
                        {
                            Id = 59,
                            EsCorrecta = false,
                            PreguntaId = 15,
                            TextoRespuesta = "Johann Sebastian Bach"
                        },
                        new
                        {
                            Id = 60,
                            EsCorrecta = false,
                            PreguntaId = 15,
                            TextoRespuesta = "Richard Wagner"
                        });
                });

            modelBuilder.Entity("Millonario.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Millonario.Domain.Record", b =>
                {
                    b.HasOne("Millonario.Domain.Usuario", "Usuario")
                        .WithMany("Records")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Millonario.Domain.Respuesta", b =>
                {
                    b.HasOne("Millonario.Domain.Pregunta", "Pregunta")
                        .WithMany("Respuestas")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("Millonario.Domain.Pregunta", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("Millonario.Domain.Usuario", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
